# volumes:
#   pg_data:

services:
  api-books:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - ./:/app
    ports:
      - "3000:3000" #http port
      - "3001:3001" #grpc port
    depends_on:
      - db
      - cache

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  cache:
    image: redis:latest
    expose:
      - 6379
    # ports:
    # - "6379:6379"
