name: CD for Go Application

on:
  push:
    branches:
      - main
  # pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Allows pushing tags and creating releases
      issues: write     # Allows commenting on issues on failure
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetches all history for all branches and tags
          # This is required for semantic-release to determine the next version
          fetch-depth: 0
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}