name: CD for Go Application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    # Add this permissions block
    permissions:
      contents: write # to push new tags and releases
      issues: write   # to comment on issues on failure
      pull-requests: write # to comment on pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          # Use the built-in GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Uncomment if you are publishing to npm