name: CD for Go Application

on:
  push:
    branches:
      - main
      - fix/semantic-release

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
      published: ${{ steps.semantic.outputs.new_release_published }}

    steps:
      - uses: actions/checkout@v4
      - name: Run Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.0.0
          dry_run: false  # Change to false after testing
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.CD_GO }}

  test:
    needs: release
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: print version
        run:  |
          echo ${{ needs.release.outputs.version }}
